"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from math import sqrt

def divisor_generator(n):
    for i in xrange(1,int(sqrt(n))+1):
        if n%i == 0:
            yield i;
            yield n/i;

def uniqify(seq):
	return set(seq)

def get_num_divisors(n):
	divisors = []
	for i in divisor_generator(n):
		divisors.append(i)
	return len(uniqify(divisors))

def get_triangle_number(n):
	triangle_number = 0
	for i in xrange(n):
		triangle_number += i
	return triangle_number

num = 0
while True:
	num += 1
	triangle_number = get_triangle_number(num)
	if get_num_divisors(triangle_number) > 500:
		print triangle_number
		break
